#include "cbase.h"

static unsigned char g_Script_vscript_client[]= {
"//========== Copyright © 2008, Valve Corporation, All rights reserved. ========\n"
"//\n"
"// Purpose:\n"
"//\n"
"//=============================================================================\n"
"\n"
"function UniqueString(string = \"\")\n"
"{\n"
"	return DoUniqueString(string.tostring());\n"
"}\n"
"\n"
"function IncludeScript(name, scope = null)\n"
"{"
"	if (scope == null)\n"
"	{\n"
"		scope = this;\n"
"	}\n"
"	return ::DoIncludeScript(name, scope); \n"
"}\n"
"\n"
};
